cache: apt
env:
    - TOOL="i686-w64-mingw32" # 32bit MinGW
    - TOOL="x86_64-w64-mingw32" # 64bit MinGW
# Install dependencies
install:
    - git clone git://github.com/LuaDist/Tools.git ~/_tools
    - ~/_tools/travis/travis install

# Bootstap
before_script:
  - ~/_tools/travis/travis bootstrap
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y lua5.1
  - sudo apt-get install -y liblua5.1*
  - sudo apt-get install -y wine1.7

# Build the module
script:
    - ~/_tools/travis/travis build
# Execute additional tests or commands
after_script:
    - ~/_tools/travis/travis test
