os:
  - linux

cache: apt

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y mingw32-runtime mingw32-binutils mingw32
  - sudo apt-get install -y wine1.7
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y lua5.1
  - sudo apt-get install -y liblua5.1*

language: c
compiler:
  - gcc

script:
    - cd code
    - git apply ../patches/*.txt
    - sudo bjam toolset=gcc install
    - sudo bjam toolset=gcc test
